### ISSUE TITLE
Debian has renamed lib32gcc1 (11/Bullseye)

### ISSUE THREAD

**Issue by obendev** [thelastnoc/dayz-sa_linuxserver#33]
Error when using dayz_setup.sh on Debian 11 (Bullseye)
The script continues. There should be a catch error
```
Package lib32gcc1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  lib32gcc-s1

E: Package 'lib32gcc1' has no installation candidate
```
https://packages.debian.org/bullseye/lib32gcc-s1
https://github.com/thelastnoc/dayz-sa_linuxserver/blob/93797803829e9569e1f11c19a01c2df40e8d97ca/script/dayz_setup.sh#L20
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
# apt-cache search lib32gcc1
lib32gcc-s1-amd64-cross - GCC support library (32 bit Version)
lib32gcc-s1-s390x-cross - GCC support library (32 bit Version)
lib32gcc-s1-mips64-cross - GCC support library (32 bit Version)
lib32gcc-s1-mips64el-cross - GCC support library (32 bit Version)
lib32gcc-s1-mips64r6-cross - GCC support library (32 bit Version)
lib32gcc-s1-mips64r6el-cross - GCC support library (32 bit Version)
lib32gcc-s1-ppc64-cross - GCC support library (32 bit Version)
lib32gcc-s1-sparc64-cross - GCC support library (32 bit Version)
lib32gcc-s1-x32-cross - GCC support library (32 bit Version)
```

**Comment by obendev** [comment]
https://packages.debian.org/bullseye/lib32gcc-s1

**Comment by obendev** [comment]
Also, why is htop and nano being installed?
The nano commands could be achieved using vi

**Comment by thelastnoc** [comment]
hello obendev

The dayz_setup.sh script isn't uses anymore since the release of the linux server files with version 1.14 experimental 8 months ago.
Consider it obsolete. It's still up for archive reasons and in the Steam Guide it's not mentioned anymore.

Nano and htop are being installed for supporting reasons.
They are simple to use and easy to explain for user without linux knowledge.
I have to keep in mind that my script will also be used from player with basic linux knowledge

But you are free to use whatever you want and modify the script for your needs.
